import { createTemporaryDatabase } from "./support/persistence/temporaryDatabase.js";
import { createBudget } from "../packages/budget-engine/src/services/createBudget.js";
import { createAccount } from "../packages/budget-engine/src/services/createAccount.js";
import { createCategoryGroup } from "../packages/budget-engine/src/services/createCategoryGroup.js";
import { createCategory } from "../packages/budget-engine/src/services/createCategory.js";
import { createTransaction } from "../packages/budget-engine/src/services/createTransaction.js";
import { AccountType } from "../packages/types/src/AccountType.js";
import { BudgetParticipation } from "../packages/types/src/BudgetParticipation.js";
import { SqliteBudgetRepository } from "../packages/repository/src/SqliteBudgetRepository.js";
import { SqliteAccountRepository } from "../packages/repository/src/SqliteAccountRepository.js";
import { SqliteCategoryGroupRepository } from "../packages/repository/src/SqliteCategoryGroupRepository.js";
import { SqliteCategoryRepository } from "../packages/repository/src/SqliteCategoryRepository.js";
import { SqliteCategoryMonthRepository } from "../packages/repository/src/SqliteCategoryMonthRepository.js";
import { SqliteTransactionRepository } from "../packages/repository/src/SqliteTransactionRepository.js";
import { CategoryMergeApplicationService } from "../packages/application/src/CategoryMergeApplicationService.js";

const { db, cleanup } = createTemporaryDatabase("budget-v126-category-merge");
const budgetRepo = new SqliteBudgetRepository(db);
const accountRepo = new SqliteAccountRepository(db);
const groupRepo = new SqliteCategoryGroupRepository(db);
const categoryRepo = new SqliteCategoryRepository(db);
const categoryMonthRepo = new SqliteCategoryMonthRepository(db);
const txRepo = new SqliteTransactionRepository(db);
const service = new CategoryMergeApplicationService(categoryRepo, categoryMonthRepo, txRepo);
const budget = createBudget("v1.2.6 Category Merge", "AUD");
await budgetRepo.create(budget);
const account = createAccount(budget.id, "Everyday", AccountType.Checking, BudgetParticipation.OnBudget, 0);
await accountRepo.create(account);
const group = createCategoryGroup(budget.id, "Everyday", 1); await groupRepo.create(group);
const source = createCategory(group.id, "Dining", 1); const target = createCategory(group.id, "Restaurants", 2);
await categoryRepo.create(source); await categoryRepo.create(target);
const tx = createTransaction({ budgetId: budget.id, accountId: account.id, categoryId: source.id, date: "2026-06-17", amount: -2500 });
await txRepo.create(tx);
const result = await service.mergeCategories(source.id, target.id, budget.id);
if (result.movedTransactions !== 1) throw new Error("Expected transaction reassignment during merge");
const moved = await txRepo.getById(tx.id);
if (moved?.categoryId !== target.id) throw new Error("Expected transaction category to move to target");
console.log("v1.2.6 category merge foundation OK");
cleanup();
