import { randomUUID } from "crypto";
import { createTemporaryDatabase } from "./support/persistence/temporaryDatabase.js";
import { createBudget } from "../packages/budget-engine/src/services/createBudget.js";
import { DomainEventType } from "../packages/types/src/DomainEventType.js";
import { SqliteBudgetRepository } from "../packages/repository/src/SqliteBudgetRepository.js";
import { SqliteDomainEventRepository } from "../packages/repository/src/SqliteDomainEventRepository.js";
import { SqliteUndoRecordRepository } from "../packages/repository/src/SqliteUndoRecordRepository.js";
import { AuditApplicationService } from "../packages/application/src/AuditApplicationService.js";
import { UndoService } from "../packages/application/src/UndoService.js";
import { CommandHistoryApplicationService } from "../packages/application/src/CommandHistoryApplicationService.js";

const { db, cleanup } = createTemporaryDatabase("budget-v128-undo-redo");
const budgetRepo = new SqliteBudgetRepository(db);
const eventRepo = new SqliteDomainEventRepository(db);
const undoRepo = new SqliteUndoRecordRepository(db);
const audit = new AuditApplicationService(eventRepo);
const undo = new UndoService(eventRepo);
const history = new CommandHistoryApplicationService(undoRepo, eventRepo);

const budget = createBudget("v1.2.8 Undo Redo", "AUD");
await budgetRepo.create(budget);
const transactionId = randomUUID();
const event = await audit.record({ budgetId: budget.id, type: DomainEventType.TransactionCreated, entityId: transactionId, payload: { amount: -1000 } });
const undoRecord = undo.createUndoRecord(budget.id, event, { action: "deleteTransaction", transactionId });
await undoRepo.create(undoRecord);
const preview = await history.previewUndo(budget.id);
if (!preview || preview.event?.id !== event.id) throw new Error("Expected undo preview to reference last audited event");
if ((preview.reversePayload as any).transactionId !== transactionId) throw new Error("Expected reverse payload to be persisted");
console.log("v1.2.8 command history undo/redo foundation OK");
cleanup();
