import assert from "node:assert/strict";
import { createPayeeService, readPayees } from "../apps/web/src/features/accounts/payeeService.ts";
import { PAYEE_ENTITY_INDEX_KEY, PAYEE_ENTITY_RECORD_PREFIX } from "../apps/web/src/features/accounts/entities/payeeEntity.ts";
const values=new Map<string,string>();
const storage={getItem:(k:string)=>values.get(k)??null,setItem:(k:string,v:string)=>{values.set(k,v)},removeItem:(k:string)=>{values.delete(k)},listKeys:()=>[...values.keys()]};
const service=createPayeeService({storage});
await service.recordPayee("Woolworths");
const [payee]=readPayees(storage);
assert.equal(payee.name,"Woolworths");
assert.ok(storage.getItem(PAYEE_ENTITY_INDEX_KEY));
assert.ok(storage.listKeys().some(k=>k.startsWith(PAYEE_ENTITY_RECORD_PREFIX)));
assert.equal(storage.getItem("budget-app.payees.v1"),null);
await service.updatePayee({id:payee.id,name:"Woolworths Metro",note:"Groceries",importRules:[]});
assert.equal(readPayees(storage)[0]?.note,"Groceries");
await service.archivePayee(payee.id);
assert.equal(await service.listPayees().then(x=>x.length),0);
assert.equal((await service.listArchivedPayees())[0]?.name,"Woolworths Metro");
console.log("PASS: Payees persist as replicated entities without budget-app.payees.v1");
