import { createEntityRepository, createHybridTimestamp, createJsonReplicatedEntityCodec, createLwwRegister, type EntityRecordStorage, type ReplicatedEntity } from "../../../../../../packages/sync/src/browser.js";
import type { KeyValueStoragePort } from "../../persistence/keyValueStoragePort.js";
export const TRANSACTION_IMPORT_PREFERENCE_ENTITY_ID="transaction-import";
export const TRANSACTION_IMPORT_PREFERENCE_ENTITY_INDEX_KEY="budget-app.entity-replication.v1/transaction-import-preference-index";
export interface TransactionImportPreferenceEntityValue { id:string; excludeMemos?:boolean; updateMatchedTransactionDates:boolean; }
const adapter=(s:KeyValueStoragePort):EntityRecordStorage=>({getItem:k=>s.getItem(k),setItem:(k,v)=>s.setItem(k,v),removeItem:k=>s.removeItem(k),listKeys:()=>s.listKeys?.()??[],flush:s.flush?()=>s.flush!():undefined});
const valid=(f:Readonly<Record<string,unknown>>):f is TransactionImportPreferenceEntityValue & Readonly<Record<string,unknown>>=>f.id===TRANSACTION_IMPORT_PREFERENCE_ENTITY_ID&&(f.excludeMemos===undefined||typeof f.excludeMemos==="boolean")&&typeof f.updateMatchedTransactionDates==="boolean";
export function createTransactionImportPreferenceEntityRepository(storage:KeyValueStoragePort){const base=createEntityRepository<TransactionImportPreferenceEntityValue>({entityType:"transaction-import-preference",storage:adapter(storage),codec:createJsonReplicatedEntityCodec(valid)});return{get:(id:string)=>base.get(id),save(e:ReplicatedEntity<TransactionImportPreferenceEntityValue>){base.save(e);storage.setItem(TRANSACTION_IMPORT_PREFERENCE_ENTITY_INDEX_KEY,JSON.stringify([TRANSACTION_IMPORT_PREFERENCE_ENTITY_ID]));}}}
export function readTransactionImportPreferenceEntity(storage:KeyValueStoragePort){const e=createTransactionImportPreferenceEntityRepository(storage).get(TRANSACTION_IMPORT_PREFERENCE_ENTITY_ID);return !e||e.metadata.tombstone?null:{id:e.fields.id.value,excludeMemos:e.fields.excludeMemos?.value??false,updateMatchedTransactionDates:e.fields.updateMatchedTransactionDates.value};}
export function writeTransactionImportPreferenceEntity(storage:KeyValueStoragePort,preferences:{excludeMemos:boolean;updateMatchedTransactionDates:boolean},now=new Date()){const r=createTransactionImportPreferenceEntityRepository(storage),c=r.get(TRANSACTION_IMPORT_PREFERENCE_ENTITY_ID),ts=createHybridTimestamp(now.getTime(),0,"transaction-import-preference-service");r.save(Object.freeze({metadata:Object.freeze(c?{...c.metadata,tombstone:null}:{id:TRANSACTION_IMPORT_PREFERENCE_ENTITY_ID,createdAt:ts,tombstone:null}),fields:Object.freeze({id:c?.fields.id??createLwwRegister(TRANSACTION_IMPORT_PREFERENCE_ENTITY_ID,ts),excludeMemos:c?.fields.excludeMemos?.value===preferences.excludeMemos?c.fields.excludeMemos:createLwwRegister(preferences.excludeMemos,ts),updateMatchedTransactionDates:c&&c.fields.updateMatchedTransactionDates.value===preferences.updateMatchedTransactionDates?c.fields.updateMatchedTransactionDates:createLwwRegister(preferences.updateMatchedTransactionDates,ts)})}));}
