import { mkdir, readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import * as simpleIcons from "simple-icons";

interface ExpansionEntry {
  readonly key: string;
  readonly title: string;
  readonly slug: string;
  readonly hex: string;
  readonly source: string;
  readonly shard: number;
}

interface SimpleIcon {
  readonly title: string;
  readonly slug: string;
  readonly hex: string;
  readonly path: string;
}

const root = process.cwd();
const checkOnly = process.argv.includes("--check");
const manifestPath = resolve(root, "tools/merchant-icons/manifests/simple-icons-expansion.json");
const manifest = JSON.parse(await readFile(manifestPath, "utf8")) as {
  readonly version: number;
  readonly sourceCollection: string;
  readonly sourceVersion: string;
  readonly entries: readonly ExpansionEntry[];
};

if (
  manifest.version !== 1 ||
  manifest.sourceCollection !== "Simple Icons" ||
  manifest.sourceVersion !== "16.32.0" ||
  manifest.entries.length !== 1750
) {
  throw new TypeError("Simple Icons expansion manifest must contain the frozen 1,750-brand v1 selection from 16.32.0.");
}

const packageIcons = Object.values(simpleIcons).filter((value): value is SimpleIcon => {
  return Boolean(
    value &&
    typeof value === "object" &&
    "slug" in value &&
    "title" in value &&
    "hex" in value &&
    "path" in value,
  );
});
const iconsBySlug = new Map(packageIcons.map((icon) => [icon.slug, icon] as const));

const expectedFiles = new Map<string, string>();
const entriesByShard = new Map<number, ExpansionEntry[]>();
for (const entry of manifest.entries) {
  const icon = iconsBySlug.get(entry.slug);
  if (!icon) throw new TypeError(`Simple Icons package is missing ${entry.slug} (${entry.title}).`);
  if (icon.title !== entry.title || icon.hex.toLocaleUpperCase() !== entry.hex.toLocaleUpperCase()) {
    throw new TypeError(`Simple Icons metadata drifted for ${entry.key}; review before regenerating.`);
  }
  const values = entriesByShard.get(entry.shard) ?? [];
  values.push(entry);
  entriesByShard.set(entry.shard, values);
}

for (const [shard, entries] of [...entriesByShard].sort(([left], [right]) => left - right)) {
  const symbols = entries.map((entry) => {
    const icon = iconsBySlug.get(entry.slug)!;
    return `<symbol id="si-${entry.slug}" viewBox="0 0 24 24"><path fill="#${icon.hex}" d="${icon.path}"/></symbol>`;
  });
  const name = `community-simple-icons-${String(shard).padStart(2, "0")}.svg`;
  expectedFiles.set(
    resolve(root, "apps/web/public/merchant-icons", name),
    `<svg xmlns="http://www.w3.org/2000/svg"><defs>${symbols.join("")}</defs></svg>\n`,
  );
}

const titleDelimiter = "\u001f";
if (manifest.entries.some(({ title }) => title.includes(titleDelimiter))) {
  throw new TypeError("Simple Icons title contains the generated-catalogue delimiter.");
}
const titles = manifest.entries.map(({ title }) => title).join(titleDelimiter);
const catalogueSource = `// Generated by tools/merchant-icons/generate-simple-icons-expansion.ts. Do not edit by hand.
import type { MerchantIconCatalogueEntry } from "./merchantIconCatalogue.js";

const TITLES = ${JSON.stringify(titles)}.split("\\u001f");
const GLOBAL = ["GLOBAL"] as const;
const REVIEWED_COMMUNITY = { kind: "community" as const, reviewed: true };

const replacements: Readonly<Record<string, string>> = {
  "+": "plus", ".": "dot", "&": "and", "đ": "d", "ħ": "h", "ı": "i",
  "ĸ": "k", "ŀ": "l", "ł": "l", "ß": "ss", "ŧ": "t", "ø": "o",
};

function simpleIconSlug(title: string): string {
  return title
    .toLocaleLowerCase()
    .replace(/[+.&đħıĸŀłßŧø]/gu, (character) => replacements[character] ?? character)
    .normalize("NFD")
    .replace(/[^a-z\\d]/gu, "");
}

export const SIMPLE_BRAND_ICON_EXPANSION: readonly MerchantIconCatalogueEntry[] = TITLES.map((name, index) => {
  const slug = simpleIconSlug(name);
  const shard = String(Math.floor(index / 40) + 1).padStart(2, "0");
  return {
    key: \`si-\${slug}-global\`,
    name,
    regions: GLOBAL,
    aliases: [],
    category: "other",
    provenance: REVIEWED_COMMUNITY,
    asset: {
      kind: "sprite",
      spritePath: \`community-simple-icons-\${shard}.svg\`,
      symbolId: \`si-\${slug}\`,
    },
  };
});
`;
expectedFiles.set(
  resolve(root, "apps/web/src/features/icons/merchantIconSimpleBrands.ts"),
  catalogueSource,
);

const provenance = {
  version: 1,
  collection: "Simple Icons",
  collectionSource: "https://github.com/simple-icons/simple-icons",
  entries: manifest.entries.map((entry) => ({
    key: entry.key,
    asset: {
      kind: "sprite",
      spritePath: `community-simple-icons-${String(entry.shard).padStart(2, "0")}.svg`,
      symbolId: `si-${entry.slug}`,
    },
    source: entry.source,
  })),
};
expectedFiles.set(
  resolve(root, "tools/merchant-icons/manifests/reviewed-simple-icons-assets.json"),
  JSON.stringify(provenance, null, 2) + "\n",
);

async function assertMatches(path: string, expected: string): Promise<void> {
  let actual = "";
  try {
    actual = await readFile(path, "utf8");
  } catch {
    throw new Error(`Missing generated Simple Icons expansion file: ${path}`);
  }
  if (actual !== expected) throw new Error(`Generated Simple Icons expansion is stale: ${path}`);
}

if (checkOnly) {
  for (const [path, expected] of expectedFiles) await assertMatches(path, expected);
  console.log(`Simple Icons expansion is current: ${manifest.entries.length} brands across ${entriesByShard.size} sprite shards.`);
} else {
  await mkdir(resolve(root, "apps/web/public/merchant-icons"), { recursive: true });
  for (const [path, expected] of expectedFiles) await writeFile(path, expected);
  console.log(`Generated ${manifest.entries.length} reviewed brand icons across ${entriesByShard.size} sprite shards.`);
}
