import { copyFile, mkdir, readFile, stat, writeFile } from "node:fs/promises";
import { basename, extname, join, resolve } from "node:path";

interface BatchEntry {
  readonly sourceFile: string;
  readonly key: string;
  readonly name: string;
  readonly regions: readonly string[];
  readonly aliases?: readonly string[];
  readonly include?: boolean;
}

interface BatchManifest {
  readonly batch: string;
  readonly entries: readonly BatchEntry[];
}

const args = new Map<string, string>();
for (let index = 2; index < process.argv.length; index += 2) {
  const key = process.argv[index];
  const value = process.argv[index + 1];
  if (!key?.startsWith("--") || !value) {
    console.error("Usage: tsx tools/merchant-icons/import-catalogue-batch.ts --source <directory> --manifest <manifest.json>");
    process.exit(2);
  }
  args.set(key.slice(2), value);
}

const sourceDirectory = args.get("source");
const manifestPath = args.get("manifest");
if (!sourceDirectory || !manifestPath) {
  console.error("Both --source and --manifest are required.");
  process.exit(2);
}

const manifest = JSON.parse(await readFile(resolve(manifestPath), "utf8")) as BatchManifest;
if (!manifest.batch || !Array.isArray(manifest.entries)) {
  throw new TypeError("Merchant icon batch manifest is invalid.");
}

const keyPattern = /^[a-z0-9]+(?:-[a-z0-9]+)*$/u;
const allowedExtensions = new Set([".svg", ".png", ".jpg", ".jpeg", ".webp"]);
const seenKeys = new Set<string>();
const included = manifest.entries.filter((entry) => entry.include !== false);
const outputDirectory = resolve("apps/web/public/merchant-icons", manifest.batch);
await mkdir(outputDirectory, { recursive: true });

const generatedEntries: string[] = [];
for (const entry of included) {
  if (!keyPattern.test(entry.key)) throw new TypeError(`Invalid merchant key: ${entry.key}`);
  if (seenKeys.has(entry.key)) throw new TypeError(`Duplicate merchant key in batch: ${entry.key}`);
  seenKeys.add(entry.key);
  if (!entry.name.trim()) throw new TypeError(`Merchant ${entry.key} has no display name.`);
  if (!entry.regions?.length) throw new TypeError(`Merchant ${entry.key} has no region.`);

  const extension = extname(entry.sourceFile).toLocaleLowerCase();
  if (!allowedExtensions.has(extension)) {
    throw new TypeError(`Unsupported merchant image format for ${entry.sourceFile}.`);
  }

  const inputPath = resolve(sourceDirectory, entry.sourceFile);
  const metadata = await stat(inputPath);
  if (!metadata.isFile() || metadata.size <= 0) {
    throw new TypeError(`Merchant image is missing or empty: ${entry.sourceFile}`);
  }

  const outputName = `${entry.key}${extension}`;
  await copyFile(inputPath, join(outputDirectory, outputName));
  const aliases = JSON.stringify(entry.aliases ?? []);
  const regions = JSON.stringify(entry.regions);
  generatedEntries.push(
    `  { key: ${JSON.stringify(entry.key)}, name: ${JSON.stringify(entry.name)}, regions: ${regions}, aliases: ${aliases}, asset: { kind: "image", assetPath: ${JSON.stringify(`${manifest.batch}/${outputName}`)} } },`,
  );
}

const generatedPath = resolve("apps/web/src/features/icons/merchantIconImportedBatch.ts");
const generatedSource =
  `// Generated by tools/merchant-icons/import-catalogue-batch.ts. Do not edit by hand.\n` +
  `import type { MerchantIconCatalogueEntry } from "./merchantIconCatalogue.js";\n\n` +
  `export const IMPORTED_MERCHANT_ICON_BATCH: readonly MerchantIconCatalogueEntry[] = [\n` +
  generatedEntries.join("\n") +
  `\n];\n`;

await writeFile(generatedPath, generatedSource);
console.log(
  `Imported ${included.length} merchant icons from ${basename(resolve(sourceDirectory))} into ${manifest.batch}.`,
);
console.log(`Generated catalogue batch: ${generatedPath}`);
