import type { MerchantIconCatalogueEntry } from "./merchantIconCatalogue.js";

export const GOVERNMENT_MERCHANT_ICON_EXPANSION: readonly MerchantIconCatalogueEntry[] = [
  {
    key: "gov-internal-revenue-service-us",
    name: "Internal Revenue Service",
    regions: ["US"],
    aliases: ["IRS"],
    category: "government",
    provenance: { kind: "official", reviewed: true },
    asset: { kind: "image", assetPath: "official/government/gov-internal-revenue-service-us.ico" },
  },
  {
    key: "gov-social-security-administration-us",
    name: "Social Security Administration",
    regions: ["US"],
    aliases: ["SSA"],
    category: "government",
    provenance: { kind: "official", reviewed: true },
    asset: { kind: "image", assetPath: "official/government/gov-social-security-administration-us.png" },
  },
  {
    key: "gov-immigration-and-customs-enforcement-us",
    name: "Immigration and Customs Enforcement",
    regions: ["US"],
    aliases: ["ICE","U.S. Immigration and Customs Enforcement"],
    category: "government",
    provenance: { kind: "official", reviewed: true },
    asset: { kind: "image", assetPath: "official/government/gov-immigration-and-customs-enforcement-us.ico" },
  },
  {
    key: "gov-federal-election-commission-us",
    name: "Federal Election Commission",
    regions: ["US"],
    aliases: ["FEC"],
    category: "government",
    provenance: { kind: "official", reviewed: true },
    asset: { kind: "image", assetPath: "official/government/gov-federal-election-commission-us.png" },
  },
  {
    key: "gov-transportation-security-administration-us",
    name: "Transportation Security Administration",
    regions: ["US"],
    aliases: ["TSA"],
    category: "government",
    provenance: { kind: "official", reviewed: true },
    asset: { kind: "image", assetPath: "official/government/gov-transportation-security-administration-us.ico" },
  },
  {
    key: "gov-revenue-nsw-nsw-au",
    name: "Revenue NSW",
    regions: ["AU"],
    aliases: [],
    category: "government",
    provenance: { kind: "official", reviewed: true },
    asset: { kind: "image", assetPath: "official/government/gov-revenue-nsw-nsw-au.png" },
  },
  {
    key: "gov-nsw-electoral-commission-nsw-au",
    name: "NSW Electoral Commission",
    regions: ["AU"],
    aliases: [],
    category: "government",
    provenance: { kind: "official", reviewed: true },
    asset: { kind: "image", assetPath: "official/government/gov-nsw-electoral-commission-nsw-au.png" },
  },
  {
    key: "gov-office-of-the-work-health-and-safety-commissioner-worksafe-act-act-au",
    name: "Office of the Work Health and Safety Commissioner (WorkSafe ACT)",
    regions: ["AU"],
    aliases: ["WorkSafe ACT"],
    category: "government",
    provenance: { kind: "official", reviewed: true },
    asset: { kind: "image", assetPath: "official/government/gov-office-of-the-work-health-and-safety-commissioner-worksafe-act-act-au.png" },
  },
  {
    key: "gov-transport-canberra-act-au",
    name: "Transport Canberra",
    regions: ["AU"],
    aliases: [],
    category: "transport",
    provenance: { kind: "official", reviewed: true },
    asset: { kind: "image", assetPath: "official/government/gov-transport-canberra-act-au.ico" },
  },
  {
    key: "gov-western-australian-electoral-commission-wa-au",
    name: "Western Australian Electoral Commission",
    regions: ["AU"],
    aliases: ["WA Electoral Commission"],
    category: "government",
    provenance: { kind: "official", reviewed: true },
    asset: { kind: "image", assetPath: "official/government/gov-western-australian-electoral-commission-wa-au.ico" },
  }
] as const;
