// Generated from tools/merchant-icons/manifests/user-seed.json.
import type { MerchantIconCatalogueEntry } from "./merchantIconCatalogue.js";

export const IMPORTED_MERCHANT_ICON_BATCH: readonly MerchantIconCatalogueEntry[] = [
  { key: "yarra-valley-water-au", name: "Yarra Valley Water", regions: ["AU"], aliases: ["YarraValleyWater"], asset: { kind: "sprite", spritePath: "user-seed-08.svg", symbolId: "yarra-valley-water-au" } },
  { key: "1st-energy-au", name: "1st Energy", regions: ["AU"], aliases: ["1stEnergy"], asset: { kind: "sprite", spritePath: "user-seed-01.svg", symbolId: "1st-energy-au" } },
  { key: "7-eleven-au", name: "7-Eleven", regions: ["AU"], aliases: [], asset: { kind: "sprite", spritePath: "user-seed-01.svg", symbolId: "7-eleven-au" } },
  { key: "adelaide-metro-au", name: "Adelaide Metro", regions: ["AU"], aliases: [], asset: { kind: "sprite", spritePath: "user-seed-01.svg", symbolId: "adelaide-metro-au" } },
  { key: "afl-record-au", name: "AFL Record", regions: ["AU"], aliases: [], asset: { kind: "sprite", spritePath: "user-seed-01.svg", symbolId: "afl-record-au" } },
  { key: "agl-au", name: "AGL", regions: ["AU"], aliases: [], asset: { kind: "sprite", spritePath: "user-seed-01.svg", symbolId: "agl-au" } },
  { key: "aliexpress-au", name: "AliExpress", regions: ["AU"], aliases: [], asset: { kind: "sprite", spritePath: "user-seed-01.svg", symbolId: "aliexpress-au" } },
  { key: "allianz-au", name: "Allianz", regions: ["AU"], aliases: [], asset: { kind: "sprite", spritePath: "user-seed-01.svg", symbolId: "allianz-au" } },
  { key: "amaysim-au", name: "amaysim", regions: ["AU"], aliases: [], asset: { kind: "sprite", spritePath: "user-seed-01.svg", symbolId: "amaysim-au" } },
  { key: "anaconda-au", name: "Anaconda", regions: ["AU"], aliases: [], asset: { kind: "sprite", spritePath: "user-seed-01.svg", symbolId: "anaconda-au" } },
  { key: "aol-au", name: "AOL", regions: ["AU"], aliases: [], asset: { kind: "sprite", spritePath: "user-seed-01.svg", symbolId: "aol-au" } },
  { key: "apco-service-stations-au", name: "APCO Service Stations", regions: ["AU"], aliases: [], asset: { kind: "sprite", spritePath: "user-seed-01.svg", symbolId: "apco-service-stations-au" } },
  { key: "apple-au", name: "Apple", regions: ["AU"], aliases: [], asset: { kind: "sprite", spritePath: "user-seed-02.svg", symbolId: "apple-au" } },
  { key: "australian-taxation-office-au", name: "Australian Taxation Office", regions: ["AU"], aliases: ["ATO"], asset: { kind: "sprite", spritePath: "user-seed-02.svg", symbolId: "australian-taxation-office-au" } },
  { key: "augustus-gelatery-au", name: "Augustus Gelatery", regions: ["AU"], aliases: [], asset: { kind: "sprite", spritePath: "user-seed-02.svg", symbolId: "augustus-gelatery-au" } },
  { key: "australia-post-au", name: "Australia Post", regions: ["AU"], aliases: ["AusPost"], asset: { kind: "sprite", spritePath: "user-seed-02.svg", symbolId: "australia-post-au" } },
  { key: "austin-health-au", name: "Austin Health", regions: ["AU"], aliases: [], asset: { kind: "sprite", spritePath: "user-seed-02.svg", symbolId: "austin-health-au" } },
  { key: "australian-education-union-au", name: "Australian Education Union", regions: ["AU"], aliases: [], asset: { kind: "sprite", spritePath: "user-seed-02.svg", symbolId: "australian-education-union-au" } },
  { key: "ambulance-victoria-au", name: "Ambulance Victoria", regions: ["AU"], aliases: [], asset: { kind: "sprite", spritePath: "user-seed-01.svg", symbolId: "ambulance-victoria-au" } },
  { key: "bakers-choice-au", name: "Baker's Choice", regions: ["AU"], aliases: [], asset: { kind: "sprite", spritePath: "user-seed-02.svg", symbolId: "bakers-choice-au" } },
  { key: "bakers-delight-au", name: "Bakers Delight", regions: ["AU"], aliases: [], asset: { kind: "sprite", spritePath: "user-seed-02.svg", symbolId: "bakers-delight-au" } },
  { key: "bankwest-au", name: "Bankwest", regions: ["AU"], aliases: [], asset: { kind: "sprite", spritePath: "user-seed-02.svg", symbolId: "bankwest-au" } },
  { key: "banyule-and-districts-netball-association-au", name: "Banyule & Districts Netball Association", regions: ["AU"], aliases: [], asset: { kind: "sprite", spritePath: "user-seed-02.svg", symbolId: "banyule-and-districts-netball-association-au" } },
  { key: "beechworth-bakery-au", name: "Beechworth Bakery", regions: ["AU"], aliases: [], asset: { kind: "sprite", spritePath: "user-seed-02.svg", symbolId: "beechworth-bakery-au" } },
  { key: "belong-au", name: "Belong", regions: ["AU"], aliases: [], asset: { kind: "sprite", spritePath: "user-seed-02.svg", symbolId: "belong-au" } },
  { key: "best-and-less-au", name: "Best & Less", regions: ["AU"], aliases: ["Best and Less"], asset: { kind: "sprite", spritePath: "user-seed-02.svg", symbolId: "best-and-less-au" } },
  { key: "big-w-au", name: "BIG W", regions: ["AU"], aliases: ["Big W"], asset: { kind: "sprite", spritePath: "user-seed-02.svg", symbolId: "big-w-au" } },
  { key: "bonds-au", name: "Bonds", regions: ["AU"], aliases: [], asset: { kind: "sprite", spritePath: "user-seed-03.svg", symbolId: "bonds-au" } },
  { key: "boost-juice-au", name: "Boost Juice", regions: ["AU"], aliases: [], asset: { kind: "sprite", spritePath: "user-seed-03.svg", symbolId: "boost-juice-au" } },
  { key: "bws-au", name: "BWS", regions: ["AU"], aliases: [], asset: { kind: "sprite", spritePath: "user-seed-03.svg", symbolId: "bws-au" } },
  { key: "caltex-au", name: "Caltex", regions: ["AU"], aliases: [], asset: { kind: "sprite", spritePath: "user-seed-03.svg", symbolId: "caltex-au" } },
  { key: "campion-education-au", name: "Campion Education", regions: ["AU"], aliases: [], asset: { kind: "sprite", spritePath: "user-seed-03.svg", symbolId: "campion-education-au" } },
  { key: "centre-com-au", name: "Centre Com", regions: ["AU"], aliases: ["Centercom"], asset: { kind: "sprite", spritePath: "user-seed-03.svg", symbolId: "centre-com-au" } },
  { key: "chemist-warehouse-au", name: "Chemist Warehouse", regions: ["AU"], aliases: [], asset: { kind: "sprite", spritePath: "user-seed-03.svg", symbolId: "chemist-warehouse-au" } },
  { key: "chris-the-cobbler-au", name: "Chris The Cobbler", regions: ["AU"], aliases: [], asset: { kind: "sprite", spritePath: "user-seed-03.svg", symbolId: "chris-the-cobbler-au" } },
  { key: "coles-express-au", name: "Coles Express", regions: ["AU"], aliases: [], asset: { kind: "sprite", spritePath: "user-seed-03.svg", symbolId: "coles-express-au" } },
  { key: "compasspay-au", name: "CompassPay", regions: ["AU"], aliases: ["Compass Pay"], asset: { kind: "sprite", spritePath: "user-seed-03.svg", symbolId: "compasspay-au" } },
  { key: "costco-au", name: "Costco", regions: ["AU"], aliases: [], asset: { kind: "sprite", spritePath: "user-seed-03.svg", symbolId: "costco-au" } },
  { key: "delaware-north-au", name: "Delaware North", regions: ["AU"], aliases: [], asset: { kind: "sprite", spritePath: "user-seed-03.svg", symbolId: "delaware-north-au" } },
  { key: "doordash-au", name: "DoorDash", regions: ["AU"], aliases: [], asset: { kind: "sprite", spritePath: "user-seed-04.svg", symbolId: "doordash-au" } },
  { key: "dotti-au", name: "Dotti", regions: ["AU"], aliases: [], asset: { kind: "sprite", spritePath: "user-seed-04.svg", symbolId: "dotti-au" } },
  { key: "dyson-au", name: "Dyson", regions: ["AU"], aliases: [], asset: { kind: "sprite", spritePath: "user-seed-04.svg", symbolId: "dyson-au" } },
  { key: "west-ivanhoe-sporting-club-au", name: "West Ivanhoe Sporting Club", regions: ["AU"], aliases: [], asset: { kind: "sprite", spritePath: "user-seed-08.svg", symbolId: "west-ivanhoe-sporting-club-au" } },
  { key: "fiesta-mexican-restaurant-au", name: "Fiesta Mexican Restaurant", regions: ["AU"], aliases: [], asset: { kind: "sprite", spritePath: "user-seed-04.svg", symbolId: "fiesta-mexican-restaurant-au" } },
  { key: "fonda-mexican-au", name: "Fonda Mexican", regions: ["AU"], aliases: [], asset: { kind: "sprite", spritePath: "user-seed-04.svg", symbolId: "fonda-mexican-au" } },
  { key: "furbabies-dog-grooming-au", name: "Furbabies Dog Grooming", regions: ["AU"], aliases: [], asset: { kind: "sprite", spritePath: "user-seed-04.svg", symbolId: "furbabies-dog-grooming-au" } },
  { key: "furness-motors-au", name: "Furness Motors", regions: ["AU"], aliases: [], asset: { kind: "sprite", spritePath: "user-seed-04.svg", symbolId: "furness-motors-au" } },
  { key: "harvey-norman-au", name: "Harvey Norman", regions: ["AU"], aliases: [], asset: { kind: "sprite", spritePath: "user-seed-04.svg", symbolId: "harvey-norman-au" } },
  { key: "diamond-creek-hotel-au", name: "Diamond Creek Hotel", regions: ["AU"], aliases: [], asset: { kind: "sprite", spritePath: "user-seed-04.svg", symbolId: "diamond-creek-hotel-au" } },
  { key: "instantscripts-au", name: "InstantScripts", regions: ["AU"], aliases: [], asset: { kind: "sprite", spritePath: "user-seed-04.svg", symbolId: "instantscripts-au" } },
  { key: "jb-hi-fi-au", name: "JB Hi-Fi", regions: ["AU"], aliases: ["JB Hifi","JBHiFi"], asset: { kind: "sprite", spritePath: "user-seed-04.svg", symbolId: "jb-hi-fi-au" } },
  { key: "kai-mook-thai-au", name: "Kai Mook Thai", regions: ["AU"], aliases: [], asset: { kind: "sprite", spritePath: "user-seed-04.svg", symbolId: "kai-mook-thai-au" } },
  { key: "kfc-au", name: "KFC", regions: ["AU"], aliases: [], asset: { kind: "sprite", spritePath: "user-seed-04.svg", symbolId: "kfc-au" } },
  { key: "kmart-au", name: "Kmart", regions: ["AU"], aliases: [], asset: { kind: "sprite", spritePath: "user-seed-05.svg", symbolId: "kmart-au" } },
  { key: "kmart-tyre-and-auto-au", name: "Kmart Tyre & Auto", regions: ["AU"], aliases: [], asset: { kind: "sprite", spritePath: "user-seed-05.svg", symbolId: "kmart-tyre-and-auto-au" } },
  { key: "leaptel-au", name: "Leaptel", regions: ["AU"], aliases: [], asset: { kind: "sprite", spritePath: "user-seed-05.svg", symbolId: "leaptel-au" } },
  { key: "lg-spare-parts-au", name: "LG Spare Parts", regions: ["AU"], aliases: [], asset: { kind: "sprite", spritePath: "user-seed-05.svg", symbolId: "lg-spare-parts-au" } },
  { key: "lindt-chocolate-cafe-au", name: "Lindt Chocolate Cafe", regions: ["AU"], aliases: [], asset: { kind: "sprite", spritePath: "user-seed-05.svg", symbolId: "lindt-chocolate-cafe-au" } },
  { key: "liquorland-au", name: "Liquorland", regions: ["AU"], aliases: [], asset: { kind: "sprite", spritePath: "user-seed-05.svg", symbolId: "liquorland-au" } },
  { key: "lumo-energy-au", name: "Lumo Energy", regions: ["AU"], aliases: [], asset: { kind: "sprite", spritePath: "user-seed-05.svg", symbolId: "lumo-energy-au" } },
  { key: "manningham-general-practice-au", name: "Manningham General Practice", regions: ["AU"], aliases: [], asset: { kind: "sprite", spritePath: "user-seed-05.svg", symbolId: "manningham-general-practice-au" } },
  { key: "margherita-pizza-and-pasta-au", name: "Margherita Pizza & Pasta", regions: ["AU"], aliases: [], asset: { kind: "sprite", spritePath: "user-seed-05.svg", symbolId: "margherita-pizza-and-pasta-au" } },
  { key: "matchbox-au", name: "Matchbox", regions: ["AU"], aliases: [], asset: { kind: "sprite", spritePath: "user-seed-05.svg", symbolId: "matchbox-au" } },
  { key: "mcg-shop-au", name: "MCG Shop", regions: ["AU"], aliases: [], asset: { kind: "sprite", spritePath: "user-seed-05.svg", symbolId: "mcg-shop-au" } },
  { key: "melbourne-vixens-au", name: "Melbourne Vixens", regions: ["AU"], aliases: [], asset: { kind: "sprite", spritePath: "user-seed-05.svg", symbolId: "melbourne-vixens-au" } },
  { key: "mexican-kitchen-au", name: "Mexican Kitchen", regions: ["AU"], aliases: [], asset: { kind: "sprite", spritePath: "user-seed-05.svg", symbolId: "mexican-kitchen-au" } },
  { key: "myer-au", name: "Myer", regions: ["AU"], aliases: [], asset: { kind: "sprite", spritePath: "user-seed-06.svg", symbolId: "myer-au" } },
  { key: "netballconnect-au", name: "NetballConnect", regions: ["AU"], aliases: ["Netball Connect"], asset: { kind: "sprite", spritePath: "user-seed-06.svg", symbolId: "netballconnect-au" } },
  { key: "northern-motor-group-au", name: "Northern Motor Group", regions: ["AU"], aliases: [], asset: { kind: "sprite", spritePath: "user-seed-06.svg", symbolId: "northern-motor-group-au" } },
  { key: "officeworks-au", name: "Officeworks", regions: ["AU"], aliases: [], asset: { kind: "sprite", spritePath: "user-seed-06.svg", symbolId: "officeworks-au" } },
  { key: "oom-energy-au", name: "OOM Energy", regions: ["AU"], aliases: [], asset: { kind: "sprite", spritePath: "user-seed-06.svg", symbolId: "oom-energy-au" } },
  { key: "pet-circle-au", name: "Pet Circle", regions: ["AU"], aliases: [], asset: { kind: "sprite", spritePath: "user-seed-06.svg", symbolId: "pet-circle-au" } },
  { key: "peter-alexander-au", name: "Peter Alexander", regions: ["AU"], aliases: [], asset: { kind: "sprite", spritePath: "user-seed-06.svg", symbolId: "peter-alexander-au" } },
  { key: "peto-au", name: "PetO", regions: ["AU"], aliases: [], asset: { kind: "sprite", spritePath: "user-seed-06.svg", symbolId: "peto-au" } },
  { key: "racv-au", name: "RACV", regions: ["AU"], aliases: [], asset: { kind: "sprite", spritePath: "user-seed-06.svg", symbolId: "racv-au" } },
  { key: "red-rooster-au", name: "Red Rooster", regions: ["AU"], aliases: [], asset: { kind: "sprite", spritePath: "user-seed-06.svg", symbolId: "red-rooster-au" } },
  { key: "redballoon-au", name: "RedBalloon", regions: ["AU"], aliases: ["Red Balloon"], asset: { kind: "sprite", spritePath: "user-seed-06.svg", symbolId: "redballoon-au" } },
  { key: "red-energy-au", name: "Red Energy", regions: ["AU"], aliases: [], asset: { kind: "sprite", spritePath: "user-seed-06.svg", symbolId: "red-energy-au" } },
  { key: "saccas-fine-foods-au", name: "Sacca's Fine Foods", regions: ["AU"], aliases: ["Saccas Fine Foods"], asset: { kind: "sprite", spritePath: "user-seed-06.svg", symbolId: "saccas-fine-foods-au" } },
  { key: "scorptec-au", name: "Scorptec", regions: ["AU"], aliases: [], asset: { kind: "sprite", spritePath: "user-seed-07.svg", symbolId: "scorptec-au" } },
  { key: "sculli-bros-au", name: "Sculli Bros", regions: ["AU"], aliases: [], asset: { kind: "sprite", spritePath: "user-seed-07.svg", symbolId: "sculli-bros-au" } },
  { key: "sir-henry-barkly-hotel-au", name: "Sir Henry Barkly Hotel", regions: ["AU"], aliases: [], asset: { kind: "sprite", spritePath: "user-seed-07.svg", symbolId: "sir-henry-barkly-hotel-au" } },
  { key: "sixt-au", name: "SIXT", regions: ["AU"], aliases: [], asset: { kind: "sprite", spritePath: "user-seed-07.svg", symbolId: "sixt-au" } },
  { key: "specsavers-au", name: "Specsavers", regions: ["AU"], aliases: [], asset: { kind: "sprite", spritePath: "user-seed-07.svg", symbolId: "specsavers-au" } },
  { key: "spotlight-au", name: "Spotlight", regions: ["AU"], aliases: [], asset: { kind: "sprite", spritePath: "user-seed-07.svg", symbolId: "spotlight-au" } },
  { key: "square-au", name: "Square", regions: ["AU"], aliases: [], asset: { kind: "sprite", spritePath: "user-seed-07.svg", symbolId: "square-au" } },
  { key: "strandbags-au", name: "Strandbags", regions: ["AU"], aliases: [], asset: { kind: "sprite", spritePath: "user-seed-07.svg", symbolId: "strandbags-au" } },
  { key: "subway-au", name: "Subway", regions: ["AU"], aliases: [], asset: { kind: "sprite", spritePath: "user-seed-07.svg", symbolId: "subway-au" } },
  { key: "target-au", name: "Target", regions: ["AU"], aliases: ["Target Australia"], asset: { kind: "sprite", spritePath: "user-seed-07.svg", symbolId: "target-au" } },
  { key: "teachers-health-au", name: "Teachers Health", regions: ["AU"], aliases: ["TeachersHealth"], asset: { kind: "sprite", spritePath: "user-seed-07.svg", symbolId: "teachers-health-au" } },
  { key: "tgi-fridays-au", name: "TGI Fridays", regions: ["AU"], aliases: ["TGI Friday's"], asset: { kind: "sprite", spritePath: "user-seed-07.svg", symbolId: "tgi-fridays-au" } },
  { key: "the-good-guys-au", name: "The Good Guys", regions: ["AU"], aliases: ["TheGoodGuys"], asset: { kind: "sprite", spritePath: "user-seed-07.svg", symbolId: "the-good-guys-au" } },
  { key: "ticketek-au", name: "Ticketek", regions: ["AU"], aliases: [], asset: { kind: "sprite", spritePath: "user-seed-08.svg", symbolId: "ticketek-au" } },
  { key: "trybooking-au", name: "TryBooking", regions: ["AU"], aliases: ["Try Booking"], asset: { kind: "sprite", spritePath: "user-seed-08.svg", symbolId: "trybooking-au" } },
  { key: "united-minds-community-services-au", name: "United Minds Community Services", regions: ["AU"], aliases: [], asset: { kind: "sprite", spritePath: "user-seed-08.svg", symbolId: "united-minds-community-services-au" } },
  { key: "united-petroleum-au", name: "United Petroleum", regions: ["AU"], aliases: [], asset: { kind: "sprite", spritePath: "user-seed-08.svg", symbolId: "united-petroleum-au" } },
  { key: "greensborough-plaza-au", name: "Greensborough Plaza", regions: ["AU"], aliases: [], asset: { kind: "sprite", spritePath: "user-seed-04.svg", symbolId: "greensborough-plaza-au" } },
  { key: "urban-grooves-au", name: "Urban Grooves", regions: ["AU"], aliases: [], asset: { kind: "sprite", spritePath: "user-seed-08.svg", symbolId: "urban-grooves-au" } },
  { key: "vicroads-au", name: "VicRoads", regions: ["AU"], aliases: ["Vic Roads"], asset: { kind: "sprite", spritePath: "user-seed-08.svg", symbolId: "vicroads-au" } },
  { key: "yarra-city-council-parking-au", name: "Yarra City Council Parking", regions: ["AU"], aliases: [], asset: { kind: "sprite", spritePath: "user-seed-08.svg", symbolId: "yarra-city-council-parking-au" } },
  { key: "yarra-oral-and-maxillofacial-surgery-au", name: "Yarra Oral & Maxillofacial Surgery", regions: ["AU"], aliases: [], asset: { kind: "sprite", spritePath: "user-seed-08.svg", symbolId: "yarra-oral-and-maxillofacial-surgery-au" } },
  { key: "yarra-plenty-swimming-club-au", name: "Yarra Plenty Swimming Club", regions: ["AU"], aliases: [], asset: { kind: "sprite", spritePath: "user-seed-08.svg", symbolId: "yarra-plenty-swimming-club-au" } },
];
