import type { MerchantIconCatalogueEntry } from "./merchantIconCatalogue.js";

export const PRIORITY_MERCHANT_ICON_EXPANSION: readonly MerchantIconCatalogueEntry[] = [
  {
    key: "jd-sports-global",
    name: "JD Sports",
    regions: ["GLOBAL"],
    aliases: ["JD Sports Australia", "JD Sports Fashion"],
    category: "clothing",
    provenance: { kind: "community", reviewed: true },
    asset: { kind: "image", assetPath: "community/jd-sports-global.svg" },
  },
  {
    key: "shein-global",
    name: "SHEIN",
    regions: ["GLOBAL"],
    aliases: ["Shein"],
    category: "clothing",
    provenance: { kind: "community", reviewed: true },
    asset: { kind: "image", assetPath: "community/shein-global.svg" },
  },
  {
    key: "glassons-global",
    name: "Glassons",
    regions: ["GLOBAL"],
    aliases: ["Glassons Australia", "Glassons New Zealand"],
    category: "clothing",
    provenance: { kind: "community", reviewed: true },
    asset: { kind: "image", assetPath: "community/glassons-global.svg" },
  },
  {
    key: "chatgpt-global",
    name: "ChatGPT",
    regions: ["GLOBAL"],
    aliases: ["Chat GPT", "OpenAI ChatGPT"],
    category: "digital",
    provenance: { kind: "community", reviewed: true },
    asset: { kind: "image", assetPath: "community/chatgpt-global.svg" },
  },
  {
    key: "montmorency-secondary-college-au",
    name: "Montmorency Secondary College",
    regions: ["AU"],
    aliases: ["Montmorency SC"],
    category: "services",
    provenance: { kind: "community", reviewed: true },
    asset: { kind: "image", assetPath: "community/montmorency-secondary-college-au.png" },
  },
  {
    key: "regent-theatre-melbourne-au",
    name: "Regent Theatre",
    regions: ["AU"],
    aliases: ["Regent Theatre Melbourne"],
    category: "entertainment",
    provenance: { kind: "community", reviewed: true },
    asset: { kind: "image", assetPath: "community/regent-theatre-melbourne-au.jpg" },
  },
  {
    key: "snooze-au",
    name: "Snooze",
    regions: ["AU"],
    aliases: ["Snooze Australia"],
    category: "home",
    provenance: { kind: "community", reviewed: true },
    asset: { kind: "image", assetPath: "community/snooze-au.jpg" },
  },
] as const;
